#pragma once
#define TAPPING_FORCE_HOLD
#define TAPPING_TERM 250

#define AUTO_SHIFT_TIMEOUT 150
#define NO_AUTO_SHIFT_SPECIAL
#define AUTO_SHIFT_TIMEOUT_PER_KEY
// Auto Shift
#define NO_AUTO_SHIFT_ALPHA
#define AUTO_SHIFT_TIMEOUT_TAPPING_TERM
#define AUTO_SHIFT_NO_SETUP

#define AUTO_SHIFT_TIMEOUT 150
#define NO_AUTO_SHIFT_SPECIAL
#define AUTO_SHIFT_TIMEOUT_PER_KEY


#define IGNORE_MOD_TAP_INTERRUPT
#define MASTER_LEFT
